# CMake generated Testfile for 
# Source directory: C:/Users/odinl/OneDrive/Desktop/Cypha/native
# Build directory: C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_parity]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/cypha_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/native_parity.bin")
  set_tests_properties([=[native_parity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;303;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_parity]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/cypha_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/native_parity.bin")
  set_tests_properties([=[native_parity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;303;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_parity]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/cypha_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/native_parity.bin")
  set_tests_properties([=[native_parity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;303;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_parity]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/cypha_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/native_parity.bin")
  set_tests_properties([=[native_parity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;303;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_parity]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_batch_llr]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/batch_llr_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/batch_llr/sidecar.json")
  set_tests_properties([=[native_batch_llr]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;309;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_batch_llr]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/batch_llr_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/batch_llr/sidecar.json")
  set_tests_properties([=[native_batch_llr]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;309;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_batch_llr]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/batch_llr_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/batch_llr/sidecar.json")
  set_tests_properties([=[native_batch_llr]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;309;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_batch_llr]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/batch_llr_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/batch_llr/sidecar.json")
  set_tests_properties([=[native_batch_llr]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;309;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_batch_llr]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_memory_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/memory_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train")
  set_tests_properties([=[native_memory_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;314;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_memory_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/memory_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train")
  set_tests_properties([=[native_memory_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;314;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_memory_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/memory_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train")
  set_tests_properties([=[native_memory_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;314;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_memory_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/memory_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train")
  set_tests_properties([=[native_memory_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;314;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_memory_train]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_memory_train_roundtrip]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/memory_train_roundtrip.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/memory_train_roundtrip_out.cypha")
  set_tests_properties([=[native_memory_train_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;319;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_memory_train_roundtrip]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/memory_train_roundtrip.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/memory_train_roundtrip_out.cypha")
  set_tests_properties([=[native_memory_train_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;319;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_memory_train_roundtrip]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/memory_train_roundtrip.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/memory_train_roundtrip_out.cypha")
  set_tests_properties([=[native_memory_train_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;319;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_memory_train_roundtrip]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/memory_train_roundtrip.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/memory_train" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/memory_train_roundtrip_out.cypha")
  set_tests_properties([=[native_memory_train_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;319;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_memory_train_roundtrip]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_preprocessor]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/preprocessor_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor")
  set_tests_properties([=[native_preprocessor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;325;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_preprocessor]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/preprocessor_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor")
  set_tests_properties([=[native_preprocessor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;325;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_preprocessor]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/preprocessor_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor")
  set_tests_properties([=[native_preprocessor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;325;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_preprocessor]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/preprocessor_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor")
  set_tests_properties([=[native_preprocessor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;325;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_preprocessor]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_preprocessor_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/preprocessor_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit_no_scale")
  set_tests_properties([=[native_preprocessor_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;330;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_preprocessor_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/preprocessor_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit_no_scale")
  set_tests_properties([=[native_preprocessor_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;330;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_preprocessor_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/preprocessor_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit_no_scale")
  set_tests_properties([=[native_preprocessor_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;330;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_preprocessor_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/preprocessor_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/preprocessor_fit_no_scale")
  set_tests_properties([=[native_preprocessor_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;330;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_preprocessor_fit]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_csv_ingest]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/csv_ingest_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_ingest")
  set_tests_properties([=[native_csv_ingest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;336;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_csv_ingest]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/csv_ingest_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_ingest")
  set_tests_properties([=[native_csv_ingest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;336;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_csv_ingest]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/csv_ingest_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_ingest")
  set_tests_properties([=[native_csv_ingest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;336;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_csv_ingest]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/csv_ingest_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_ingest")
  set_tests_properties([=[native_csv_ingest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;336;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_csv_ingest]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_studio_trainer_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;341;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_studio_trainer_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;341;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_studio_trainer_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;341;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_studio_trainer_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;341;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_studio_trainer_preprocess_classify_hotpath]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;346;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;346;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;346;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_preprocess_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;346;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_studio_trainer_preprocess_gh_classify_hotpath]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_csv_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_preprocess_classify_hotpath")
  set_tests_properties([=[native_csv_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;351;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_csv_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_preprocess_classify_hotpath")
  set_tests_properties([=[native_csv_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;351;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_csv_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_preprocess_classify_hotpath")
  set_tests_properties([=[native_csv_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;351;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_csv_preprocess_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/preprocess_train_classify_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/csv_preprocess_classify_hotpath")
  set_tests_properties([=[native_csv_preprocess_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;351;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_csv_preprocess_classify_hotpath]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_nig_adapt]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/nig_adapt_parity.exe")
  set_tests_properties([=[native_nig_adapt]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;356;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_nig_adapt]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/nig_adapt_parity.exe")
  set_tests_properties([=[native_nig_adapt]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;356;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_nig_adapt]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/nig_adapt_parity.exe")
  set_tests_properties([=[native_nig_adapt]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;356;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_nig_adapt]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/nig_adapt_parity.exe")
  set_tests_properties([=[native_nig_adapt]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;356;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_nig_adapt]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_train_step_vector]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/train_step_vector_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/train_step_vector")
  set_tests_properties([=[native_train_step_vector]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;357;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_train_step_vector]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/train_step_vector_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/train_step_vector")
  set_tests_properties([=[native_train_step_vector]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;357;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_train_step_vector]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/train_step_vector_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/train_step_vector")
  set_tests_properties([=[native_train_step_vector]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;357;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_train_step_vector]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/train_step_vector_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/train_step_vector")
  set_tests_properties([=[native_train_step_vector]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;357;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_train_step_vector]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_dif_regressor_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/dif_regressor_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_regressor_train_step")
  set_tests_properties([=[native_dif_regressor_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;362;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_dif_regressor_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/dif_regressor_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_regressor_train_step")
  set_tests_properties([=[native_dif_regressor_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;362;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_dif_regressor_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/dif_regressor_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_regressor_train_step")
  set_tests_properties([=[native_dif_regressor_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;362;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_dif_regressor_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/dif_regressor_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_regressor_train_step")
  set_tests_properties([=[native_dif_regressor_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;362;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_dif_regressor_train_step]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_regression_mixture]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/regression_mixture_parity.exe")
  set_tests_properties([=[native_regression_mixture]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;367;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_regression_mixture]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/regression_mixture_parity.exe")
  set_tests_properties([=[native_regression_mixture]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;367;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_regression_mixture]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/regression_mixture_parity.exe")
  set_tests_properties([=[native_regression_mixture]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;367;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_regression_mixture]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/regression_mixture_parity.exe")
  set_tests_properties([=[native_regression_mixture]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;367;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_regression_mixture]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_regression_m4]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/regression_m4_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/regression_m4/sidecar.json")
  set_tests_properties([=[native_regression_m4]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;368;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_regression_m4]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/regression_m4_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/regression_m4/sidecar.json")
  set_tests_properties([=[native_regression_m4]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;368;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_regression_m4]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/regression_m4_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/regression_m4/sidecar.json")
  set_tests_properties([=[native_regression_m4]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;368;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_regression_m4]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/regression_m4_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/regression_m4/sidecar.json")
  set_tests_properties([=[native_regression_m4]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;368;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_regression_m4]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_regression_rff]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/regression_rff_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/rff_regression/sidecar.json")
  set_tests_properties([=[native_regression_rff]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;373;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_regression_rff]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/regression_rff_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/rff_regression/sidecar.json")
  set_tests_properties([=[native_regression_rff]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;373;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_regression_rff]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/regression_rff_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/rff_regression/sidecar.json")
  set_tests_properties([=[native_regression_rff]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;373;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_regression_rff]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/regression_rff_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/rff_regression/sidecar.json")
  set_tests_properties([=[native_regression_rff]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;373;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_regression_rff]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_regression_two_stage_pipeline]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/regression_two_stage_pipeline_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_pipeline/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;378;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_regression_two_stage_pipeline]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/regression_two_stage_pipeline_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_pipeline/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;378;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_regression_two_stage_pipeline]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/regression_two_stage_pipeline_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_pipeline/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;378;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_regression_two_stage_pipeline]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/regression_two_stage_pipeline_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_pipeline/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;378;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_regression_two_stage_pipeline]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_regression_two_stage_ridge_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_ridge_fit/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_ridge_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;383;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_regression_two_stage_ridge_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_ridge_fit/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_ridge_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;383;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_regression_two_stage_ridge_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_ridge_fit/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_ridge_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;383;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_regression_two_stage_ridge_fit]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_ridge_fit/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_ridge_fit]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;383;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_regression_two_stage_ridge_fit]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_regression_two_stage_e2e_ridge]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_e2e_ridge/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_e2e_ridge]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;388;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_regression_two_stage_e2e_ridge]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_e2e_ridge/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_e2e_ridge]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;388;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_regression_two_stage_e2e_ridge]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_e2e_ridge/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_e2e_ridge]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;388;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_regression_two_stage_e2e_ridge]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/regression_two_stage_ridge_fit_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/two_stage_e2e_ridge/sidecar.json")
  set_tests_properties([=[native_regression_two_stage_e2e_ridge]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;388;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_regression_two_stage_e2e_ridge]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_quantile_dif_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/quantile_dif_train")
  set_tests_properties([=[native_quantile_dif_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;393;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_quantile_dif_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/quantile_dif_train")
  set_tests_properties([=[native_quantile_dif_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;393;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_quantile_dif_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/quantile_dif_train")
  set_tests_properties([=[native_quantile_dif_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;393;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_quantile_dif_train]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/quantile_dif_train")
  set_tests_properties([=[native_quantile_dif_train]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;393;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_quantile_dif_train]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_dif_train_replay]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_train_replay")
  set_tests_properties([=[native_dif_train_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;398;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_dif_train_replay]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_train_replay")
  set_tests_properties([=[native_dif_train_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;398;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_dif_train_replay]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_train_replay")
  set_tests_properties([=[native_dif_train_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;398;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_dif_train_replay]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/dif_train_replay")
  set_tests_properties([=[native_dif_train_replay]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;398;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_dif_train_replay]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_studio_trainer_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;403;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_studio_trainer_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;403;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_studio_trainer_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;403;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_studio_trainer_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;403;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_studio_trainer_classify_hotpath]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_studio_trainer_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;408;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_studio_trainer_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;408;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_studio_trainer_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;408;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_studio_trainer_gh_classify_hotpath]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/quantile_dif_train_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/studio_trainer_gh_classify_hotpath")
  set_tests_properties([=[native_studio_trainer_gh_classify_hotpath]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;408;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_studio_trainer_gh_classify_hotpath]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_mke_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_step")
  set_tests_properties([=[native_mke_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;413;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_mke_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_step")
  set_tests_properties([=[native_mke_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;413;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_mke_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_step")
  set_tests_properties([=[native_mke_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;413;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_mke_train_step]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_step")
  set_tests_properties([=[native_mke_train_step]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;413;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_mke_train_step]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_mke_train_extended]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_extended")
  set_tests_properties([=[native_mke_train_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;418;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_mke_train_extended]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_extended")
  set_tests_properties([=[native_mke_train_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;418;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_mke_train_extended]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_extended")
  set_tests_properties([=[native_mke_train_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;418;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_mke_train_extended]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/mke_train_step_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/mke_train_extended")
  set_tests_properties([=[native_mke_train_extended]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;418;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_mke_train_extended]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_generation]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/generation_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/generation/sidecar.json")
  set_tests_properties([=[native_generation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;423;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_generation]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/generation_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/generation/sidecar.json")
  set_tests_properties([=[native_generation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;423;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_generation]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/generation_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/generation/sidecar.json")
  set_tests_properties([=[native_generation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;423;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_generation]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/generation_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/generation/sidecar.json")
  set_tests_properties([=[native_generation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;423;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_generation]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_create_model]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/create_model_smoke.exe")
  set_tests_properties([=[native_create_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;429;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_create_model]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/create_model_smoke.exe")
  set_tests_properties([=[native_create_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;429;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_create_model]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/create_model_smoke.exe")
  set_tests_properties([=[native_create_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;429;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_create_model]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/create_model_smoke.exe")
  set_tests_properties([=[native_create_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;429;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_create_model]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_cuda_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/cuda_smoke.exe")
  set_tests_properties([=[native_cuda_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;434;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_cuda_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/cuda_smoke.exe")
  set_tests_properties([=[native_cuda_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;434;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_cuda_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/cuda_smoke.exe")
  set_tests_properties([=[native_cuda_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;434;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_cuda_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/cuda_smoke.exe")
  set_tests_properties([=[native_cuda_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;434;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_cuda_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_cuda_bench]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/cuda_smoke.exe" "--bench")
  set_tests_properties([=[native_cuda_bench]=] PROPERTIES  SKIP_RETURN_CODE "2" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;439;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_cuda_bench]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/cuda_smoke.exe" "--bench")
  set_tests_properties([=[native_cuda_bench]=] PROPERTIES  SKIP_RETURN_CODE "2" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;439;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_cuda_bench]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/cuda_smoke.exe" "--bench")
  set_tests_properties([=[native_cuda_bench]=] PROPERTIES  SKIP_RETURN_CODE "2" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;439;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_cuda_bench]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/cuda_smoke.exe" "--bench")
  set_tests_properties([=[native_cuda_bench]=] PROPERTIES  SKIP_RETURN_CODE "2" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;439;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_cuda_bench]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_registry_register]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/registry_register.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/registry_native_smoke_root" "native_reg_smoke" "0.0.1" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/registry_register/card.json" "--overwrite" "--and-verify")
  set_tests_properties([=[native_registry_register]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;445;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_registry_register]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/registry_register.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/registry_native_smoke_root" "native_reg_smoke" "0.0.1" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/registry_register/card.json" "--overwrite" "--and-verify")
  set_tests_properties([=[native_registry_register]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;445;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_registry_register]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/registry_register.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/registry_native_smoke_root" "native_reg_smoke" "0.0.1" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/registry_register/card.json" "--overwrite" "--and-verify")
  set_tests_properties([=[native_registry_register]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;445;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_registry_register]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/registry_register.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/registry_native_smoke_root" "native_reg_smoke" "0.0.1" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/registry_register/card.json" "--overwrite" "--and-verify")
  set_tests_properties([=[native_registry_register]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;445;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_registry_register]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_experiment_db_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;458;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_experiment_db_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;458;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_experiment_db_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;458;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_experiment_db_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;458;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_experiment_db_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_experiment_db_file]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_db_native_roundtrip.sqlite")
  set_tests_properties([=[native_experiment_db_file]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;462;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_experiment_db_file]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_db_native_roundtrip.sqlite")
  set_tests_properties([=[native_experiment_db_file]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;462;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_experiment_db_file]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_db_native_roundtrip.sqlite")
  set_tests_properties([=[native_experiment_db_file]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;462;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_experiment_db_file]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/experiment_db_smoke.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_db_native_roundtrip.sqlite")
  set_tests_properties([=[native_experiment_db_file]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;462;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_experiment_db_file]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_experiment_db_crud]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Debug/experiment_db_crud_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_crud]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;470;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_experiment_db_crud]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/Release/experiment_db_crud_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_crud]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;470;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_experiment_db_crud]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/MinSizeRel/experiment_db_crud_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_crud]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;470;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_experiment_db_crud]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/RelWithDebInfo/experiment_db_crud_parity.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/experiment_ddl.sql")
  set_tests_properties([=[native_experiment_db_crud]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;470;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_experiment_db_crud]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_qt_stub_load_reference]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/Debug/cypha_qt_stub.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_stub_load_reference]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;481;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_qt_stub_load_reference]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/Release/cypha_qt_stub.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_stub_load_reference]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;481;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_qt_stub_load_reference]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/MinSizeRel/cypha_qt_stub.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_stub_load_reference]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;481;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_qt_stub_load_reference]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/RelWithDebInfo/cypha_qt_stub.exe" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_stub_load_reference]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;481;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_qt_stub_load_reference]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[native_qt_shell_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/Debug/cypha_qt_shell.exe" "--smoke" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_shell_smoke]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;493;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[native_qt_shell_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/Release/cypha_qt_shell.exe" "--smoke" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_shell_smoke]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;493;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[native_qt_shell_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/MinSizeRel/cypha_qt_shell.exe" "--smoke" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_shell_smoke]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;493;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[native_qt_shell_smoke]=] "C:/Users/odinl/OneDrive/Desktop/Cypha/native/build-windows-msvc/qt/RelWithDebInfo/cypha_qt_shell.exe" "--smoke" "C:/Users/odinl/OneDrive/Desktop/Cypha/parity_fixtures/reference.cypha")
  set_tests_properties([=[native_qt_shell_smoke]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;493;add_test;C:/Users/odinl/OneDrive/Desktop/Cypha/native/CMakeLists.txt;0;")
else()
  add_test([=[native_qt_shell_smoke]=] NOT_AVAILABLE)
endif()
subdirs("qt")
