"""Per-platform lifecycle specifications — unique config for every portfolio platform."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

TIER2_RATES = {
    "FTFeed": 300_000,
    "FTExtract": 150_000,
    "FTFire": 80_000,
    "FTEject": 60_000,
    "FTGas": 400_000,
    "FTPrimer": 200_000,
    "FTCase": 500_000,
}

BASELINE_RATES = {
    "FTFeed": 8_000,
    "FTExtract": 12_000,
    "FTFire": 5_000,
    "FTEject": 10_000,
    "FTGas": 15_000,
    "FTPrimer": 25_000,
    "FTCase": 40_000,
}


@dataclass
class FirearmLifecycleConfig:
    platform: str
    category: str  # firearm | crew_served
    cartridge_key: str
    action: str
    barrel_length_mm: float
    peak_pressure_MPa: float
    muzzle_velocity_ms: float
    projectile_mass_g: float
    propellant_mass_g: float
    weapon_mass_kg: float
    bolt_mass_kg: float
    spring_rate_N_per_mm: float
    bolt_stroke_mm: float
    bolt_impulse_Ns: float
    muzzle_brake_efficiency: float
    shooter_effective_mass_kg: float
    barrel_r_i_mm: float
    barrel_r_o_mm: float
    barrel_yield_MPa: float
    archard_K: float
    archard_H_GPa: float
    spring_tau_max_MPa: float
    spring_S_e_MPa: float
    bore_life_target_rounds: int
    tier2_equipped: bool
    failure_rates: Dict[str, int]
    components: List[Dict[str, object]] = field(default_factory=list)


@dataclass
class GenericLifecycleConfig:
    platform: str
    category: str  # armour | sustainment | systems | scope
    headline: Dict[str, object] = field(default_factory=dict)
    components: List[Dict[str, object]] = field(default_factory=list)
    primary_metric: str = "calendar_years"
    scope_note: Optional[str] = None
    failure_rates: Optional[Dict[str, int]] = None


PlatformConfig = FirearmLifecycleConfig | GenericLifecycleConfig


def all_platform_configs() -> Dict[str, PlatformConfig]:
    """Return lifecycle spec keyed by portfolio platform display name."""
    return {
        **_firearm_configs(),
        **_generic_configs(),
    }


def _firearm_configs() -> Dict[str, FirearmLifecycleConfig]:
    return {
        "MP-4.6P Guardian LE": FirearmLifecycleConfig(
            platform="MP-4.6P Guardian LE",
            category="firearm",
            cartridge_key="4.6x22mm",
            action="gas-operated delayed blowback",
            barrel_length_mm=150.0,
            peak_pressure_MPa=246.0,
            muzzle_velocity_ms=396.0,
            projectile_mass_g=3.3,
            propellant_mass_g=0.22,
            weapon_mass_kg=0.85,
            bolt_mass_kg=0.015,
            spring_rate_N_per_mm=0.092,
            bolt_stroke_mm=40.0,
            bolt_impulse_Ns=0.047,
            muzzle_brake_efficiency=0.42,
            shooter_effective_mass_kg=5.68,
            barrel_r_i_mm=2.3,
            barrel_r_o_mm=8.5,
            barrel_yield_MPa=690.0,
            archard_K=1.0e-14,
            archard_H_GPa=8.0,
            spring_tau_max_MPa=74.0,
            spring_S_e_MPa=428.0,
            bore_life_target_rounds=24_000,
            tier2_equipped=True,
            failure_rates=dict(TIER2_RATES),
            components=[
                {"name": "Barrel (416R + chrome + DLC ports)", "warn_rds": 18_000,
                 "fail_rds": 24_000, "model": "Archard bore erosion", "action": "REPLACE"},
                {"name": "Recoil spring (17-7 PH)", "warn_rds": 50_000,
                 "fail_rds": 120_000, "model": "Goodman infinite-life", "action": "SERVICE"},
                {"name": "Extractor hook (H13 + DLC)", "warn_rds": 40_000,
                 "fail_rds": 150_000, "model": "Hook wear + spring preload", "action": "REPLACE"},
                {"name": "Magazine feed lips (440C laser-formed)", "warn_rds": 25_000,
                 "fail_rds": 80_000, "model": "Lip spring-set", "action": "REPLACE"},
                {"name": "DLC sliding surfaces batch", "warn_rds": 15_000,
                 "fail_rds": 30_000, "model": "Coating wear budget", "action": "RECOAT"},
            ],
        ),
        "MP-4.6M Pistol": FirearmLifecycleConfig(
            platform="MP-4.6M Pistol",
            category="firearm",
            cartridge_key="4.6x30mm",
            action="rotating bolt, short recoil",
            barrel_length_mm=180.0,
            peak_pressure_MPa=180.0,
            muzzle_velocity_ms=501.0,
            projectile_mass_g=2.6,
            propellant_mass_g=0.40,
            weapon_mass_kg=0.92,
            bolt_mass_kg=0.012,
            spring_rate_N_per_mm=0.11,
            bolt_stroke_mm=35.0,
            bolt_impulse_Ns=0.038,
            muzzle_brake_efficiency=0.0,
            shooter_effective_mass_kg=8.0,
            barrel_r_i_mm=2.325,
            barrel_r_o_mm=9.0,
            barrel_yield_MPa=690.0,
            archard_K=8.0e-15,
            archard_H_GPa=12.0,
            spring_tau_max_MPa=68.0,
            spring_S_e_MPa=428.0,
            bore_life_target_rounds=75_000,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 250_000, "FTExtract": 150_000, "FTFire": 80_000,
                "FTEject": 60_000, "FTGas": 400_000, "FTPrimer": 200_000,
                "FTCase": 500_000,
            },
            components=[
                {"name": "Barrel (416R + Stellite-21 throat)", "warn_rds": 50_000,
                 "fail_rds": 75_000, "model": "Archard + Stellite erosion", "action": "REPLACE"},
                {"name": "Rotating bolt lugs (H13)", "warn_rds": 35_000,
                 "fail_rds": 50_000, "model": "S-N fatigue SF>3", "action": "INSPECT"},
                {"name": "Integral suppressor K-baffles (Inconel 718)", "warn_rds": 18_000,
                 "fail_rds": 25_000, "model": "Blast-face erosion", "action": "SERVICE"},
                {"name": "Recoil spring (MP35N)", "warn_rds": 10_000,
                 "fail_rds": 15_000, "model": "Goodman infinite-life", "action": "SERVICE"},
                {"name": "Extractor / ejector (S7 + DLC)", "warn_rds": 18_000,
                 "fail_rds": 25_000, "model": "Hook + cam wear", "action": "REPLACE"},
            ],
        ),
        "MP-4.6M Defender PDW": FirearmLifecycleConfig(
            platform="MP-4.6M Defender PDW",
            category="firearm",
            cartridge_key="4.6x30mm_PDW",
            action="rotating bolt + buffered carrier",
            barrel_length_mm=266.7,
            peak_pressure_MPa=180.0,
            muzzle_velocity_ms=542.0,
            projectile_mass_g=2.6,
            propellant_mass_g=0.40,
            weapon_mass_kg=2.10,
            bolt_mass_kg=0.018,
            spring_rate_N_per_mm=0.14,
            bolt_stroke_mm=42.0,
            bolt_impulse_Ns=0.042,
            muzzle_brake_efficiency=0.0,
            shooter_effective_mass_kg=8.0,
            barrel_r_i_mm=2.325,
            barrel_r_o_mm=10.5,
            barrel_yield_MPa=690.0,
            archard_K=6.0e-15,
            archard_H_GPa=12.0,
            spring_tau_max_MPa=82.0,
            spring_S_e_MPa=428.0,
            bore_life_target_rounds=75_000,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 220_000, "FTExtract": 150_000, "FTFire": 80_000,
                "FTEject": 60_000, "FTGas": 380_000, "FTPrimer": 200_000,
                "FTCase": 500_000,
            },
            components=[
                {"name": "Barrel (416R + Stellite-21)", "warn_rds": 50_000,
                 "fail_rds": 75_000, "model": "Archard + sustained-fire thermal", "action": "REPLACE"},
                {"name": "Buffered bolt-carrier (H13 + Ti countermass)", "warn_rds": 14_000,
                 "fail_rds": 20_000, "model": "Carrier rail wear + buffer stack", "action": "SERVICE"},
                {"name": "Integral suppressor (180 cm³ Inconel)", "warn_rds": 20_000,
                 "fail_rds": 30_000, "model": "Baffle erosion @ 850 rpm bound", "action": "SERVICE"},
                {"name": "Buffer spring stack (Elgiloy)", "warn_rds": 20_000,
                 "fail_rds": 30_000, "model": "Compression set", "action": "REPLACE"},
                {"name": "Feed ramp / magazine well (7075-T6)", "warn_rds": 18_000,
                 "fail_rds": 25_000, "model": "Peening + DLC wear", "action": "INSPECT"},
            ],
        ),
        "MP-6.8 Mark II Rifle": FirearmLifecycleConfig(
            platform="MP-6.8 Mark II Rifle",
            category="firearm",
            cartridge_key="6.8x51mm",
            action="short-stroke gas piston, rotating bolt",
            barrel_length_mm=406.0,
            peak_pressure_MPa=307.0,
            muzzle_velocity_ms=731.0,
            projectile_mass_g=8.7,
            propellant_mass_g=2.8,
            weapon_mass_kg=4.10,
            bolt_mass_kg=0.048,
            spring_rate_N_per_mm=0.28,
            bolt_stroke_mm=48.0,
            bolt_impulse_Ns=0.12,
            muzzle_brake_efficiency=0.35,
            shooter_effective_mass_kg=9.5,
            barrel_r_i_mm=3.425,
            barrel_r_o_mm=14.0,
            barrel_yield_MPa=690.0,
            archard_K=5.0e-15,
            archard_H_GPa=14.0,
            spring_tau_max_MPa=95.0,
            spring_S_e_MPa=428.0,
            bore_life_target_rounds=25_000,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 220_000, "FTExtract": 110_000, "FTFire": 55_000,
                "FTEject": 48_000, "FTGas": 320_000, "FTPrimer": 175_000,
                "FTCase": 420_000,
            },
            components=[
                {"name": "Barrel (chrome + Stellite-21 throat)", "warn_rds": 18_000,
                 "fail_rds": 25_000, "model": "Archard accuracy-retention", "action": "REPLACE"},
                {"name": "Gas piston / op-rod (Ni-Cr-Mo)", "warn_rds": 35_000,
                 "fail_rds": 80_000, "model": "Wear + carbon fouling", "action": "SERVICE"},
                {"name": "Bolt carrier group (Carpenter 158)", "warn_rds": 40_000,
                 "fail_rds": 100_000, "model": "Lug peening + cam path", "action": "INSPECT"},
                {"name": "Suppressor baffles (Inconel 718)", "warn_rds": 12_000,
                 "fail_rds": 22_000, "model": "Blast-face erosion", "action": "SERVICE"},
                {"name": "Buffer spring (chrome-silicon)", "warn_rds": 30_000,
                 "fail_rds": 70_000, "model": "Goodman infinite-life", "action": "REPLACE"},
            ],
        ),
        "MAS-15.2E Sniper": FirearmLifecycleConfig(
            platform="MAS-15.2E Sniper",
            category="firearm",
            cartridge_key="15.2x115mm",
            action="bolt action, three-lug rotating bolt",
            barrel_length_mm=900.0,
            peak_pressure_MPa=258.0,
            muzzle_velocity_ms=781.0,
            projectile_mass_g=64.0,
            propellant_mass_g=18.0,
            weapon_mass_kg=13.2,
            bolt_mass_kg=0.85,
            spring_rate_N_per_mm=1.2,
            bolt_stroke_mm=95.0,
            bolt_impulse_Ns=0.55,
            muzzle_brake_efficiency=0.65,
            shooter_effective_mass_kg=12.0,
            barrel_r_i_mm=7.6,
            barrel_r_o_mm=22.0,
            barrel_yield_MPa=690.0,
            archard_K=2.0e-15,
            archard_H_GPa=18.0,
            spring_tau_max_MPa=120.0,
            spring_S_e_MPa=428.0,
            bore_life_target_rounds=1_500,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 500_000, "FTExtract": 200_000, "FTFire": 120_000,
                "FTEject": 300_000, "FTGas": 1_000_000, "FTPrimer": 180_000,
                "FTCase": 350_000,
            },
            components=[
                {"name": "Barrel (Stellite-21 lined, quick-change)", "warn_rds": 1_000,
                 "fail_rds": 1_500, "model": "Throat erosion / sub-MOA bound", "action": "REPLACE"},
                {"name": "Integral suppressor (Inconel K-baffles)", "warn_rds": 1_000,
                 "fail_rds": 1_500, "model": "Blast-face erosion", "action": "SERVICE"},
                {"name": "Bolt lugs (Carpenter 158)", "warn_rds": 8_000,
                 "fail_rds": 20_000, "model": "Lug bearing fatigue", "action": "INSPECT"},
                {"name": "Firing pin spring (music wire)", "warn_rds": 1_400,
                 "fail_rds": 2_000, "model": "Wahl fatigue", "action": "REPLACE"},
                {"name": "Magazine spring (17-7 PH)", "warn_rds": 1_400,
                 "fail_rds": 2_000, "model": "Compression set", "action": "REPLACE"},
            ],
        ),
        "57 mm Autocannon": FirearmLifecycleConfig(
            platform="57 mm Autocannon",
            category="crew_served",
            cartridge_key="57x347mm",
            action="dual-feed externally powered rotary",
            barrel_length_mm=4560.0,
            peak_pressure_MPa=257.0,
            muzzle_velocity_ms=948.0,
            projectile_mass_g=2400.0,
            propellant_mass_g=850.0,
            weapon_mass_kg=350.0,
            bolt_mass_kg=2.8,
            spring_rate_N_per_mm=8.5,
            bolt_stroke_mm=120.0,
            bolt_impulse_Ns=4.4,
            muzzle_brake_efficiency=0.55,
            shooter_effective_mass_kg=350.0,
            barrel_r_i_mm=28.5,
            barrel_r_o_mm=65.0,
            barrel_yield_MPa=550.0,
            archard_K=3.0e-16,
            archard_H_GPa=22.0,
            spring_tau_max_MPa=180.0,
            spring_S_e_MPa=550.0,
            bore_life_target_rounds=2_500,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 45_000, "FTExtract": 60_000, "FTFire": 35_000,
                "FTEject": 50_000, "FTGas": 80_000, "FTPrimer": 90_000,
                "FTCase": 120_000,
            },
            components=[
                {"name": "Chrome-Stellite barrel liner", "warn_rds": 800,
                 "fail_rds": 2_500, "model": "Throat erosion @ 257 MPa", "action": "REPLACE"},
                {"name": "Hydraulic recoil buffer seals", "warn_rds": 5_000,
                 "fail_rds": 10_000, "model": "Seal extrusion + fluid loss", "action": "SERVICE"},
                {"name": "Dual-feed sprocket / link belt", "warn_rds": 15_000,
                 "fail_rds": 40_000, "model": "Link fatigue + peening", "action": "INSPECT"},
                {"name": "Rotary breech cluster", "warn_rds": 20_000,
                 "fail_rds": 50_000, "model": "Cam-track wear", "action": "SERVICE"},
                {"name": "Thermal sleeve / cooling jacket", "warn_rds": 3_000,
                 "fail_rds": 8_000, "model": "80 rpm sustained thermal bound", "action": "INSPECT"},
            ],
        ),
        "57 mm Underbarrel GL": FirearmLifecycleConfig(
            platform="57 mm Underbarrel GL",
            category="firearm",
            cartridge_key="57mm_LV_grenade",
            action="single-shot break-action under-barrel",
            barrel_length_mm=280.0,
            peak_pressure_MPa=42.0,
            muzzle_velocity_ms=149.0,
            projectile_mass_g=348.0,
            propellant_mass_g=12.0,
            weapon_mass_kg=2.40,
            bolt_mass_kg=0.35,
            spring_rate_N_per_mm=0.45,
            bolt_stroke_mm=25.0,
            bolt_impulse_Ns=0.18,
            muzzle_brake_efficiency=0.0,
            shooter_effective_mass_kg=8.0,
            barrel_r_i_mm=28.5,
            barrel_r_o_mm=38.0,
            barrel_yield_MPa=550.0,
            archard_K=1.0e-15,
            archard_H_GPa=10.0,
            spring_tau_max_MPa=45.0,
            spring_S_e_MPa=428.0,
            bore_life_target_rounds=5_000,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 1_000_000, "FTExtract": 80_000, "FTFire": 40_000,
                "FTEject": 200_000, "FTGas": 500_000, "FTPrimer": 60_000,
                "FTCase": 100_000,
            },
            components=[
                {"name": "Chrome-lined launch tube", "warn_rds": 3_500,
                 "fail_rds": 5_000, "model": "Low-pressure rifling wear", "action": "INSPECT"},
                {"name": "Break-action hinge pin (17-4 PH)", "warn_rds": 2_000,
                 "fail_rds": 6_000, "model": "Bearing wear + lock-up", "action": "SERVICE"},
                {"name": "Leaf sight / quadrant mount", "warn_rds": 4_000,
                 "fail_rds": 10_000, "model": "Vibration loosening", "action": "TIGHTEN"},
                {"name": "Firing pin / striker (H13)", "warn_rds": 3_000,
                 "fail_rds": 8_000, "model": "Tip mushrooming", "action": "REPLACE"},
            ],
        ),
        "57 mm Mortar/RPG": FirearmLifecycleConfig(
            platform="57 mm Mortar/RPG",
            category="crew_served",
            cartridge_key="57mm_mortar",
            action="muzzle-loaded dual-mode tube",
            barrel_length_mm=650.0,
            peak_pressure_MPa=55.0,
            muzzle_velocity_ms=187.0,
            projectile_mass_g=1390.0,
            propellant_mass_g=45.0,
            weapon_mass_kg=7.20,
            bolt_mass_kg=0.0,
            spring_rate_N_per_mm=0.0,
            bolt_stroke_mm=0.0,
            bolt_impulse_Ns=0.0,
            muzzle_brake_efficiency=0.40,
            shooter_effective_mass_kg=80.0,
            barrel_r_i_mm=28.5,
            barrel_r_o_mm=42.0,
            barrel_yield_MPa=550.0,
            archard_K=8.0e-16,
            archard_H_GPa=10.0,
            spring_tau_max_MPa=0.0,
            spring_S_e_MPa=428.0,
            bore_life_target_rounds=8_000,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 500_000, "FTExtract": 300_000, "FTFire": 25_000,
                "FTEject": 400_000, "FTGas": 600_000, "FTPrimer": 35_000,
                "FTCase": 80_000,
            },
            components=[
                {"name": "Chrome-lined tube (muzzle-loader)", "warn_rds": 5_000,
                 "fail_rds": 8_000, "model": "Spalling + obturation ring wear", "action": "INSPECT"},
                {"name": "Baseplate / bipod pivot (7075-T6)", "warn_rds": 3_000,
                 "fail_rds": 10_000, "model": "Fretting + soil impact", "action": "SERVICE"},
                {"name": "Trigger / firing pin (RPG mode)", "warn_rds": 2_000,
                 "fail_rds": 6_000, "model": "Pin tip wear", "action": "REPLACE"},
                {"name": "Spiral-groove obturation ring", "warn_rds": 1_500,
                 "fail_rds": 4_000, "model": "Gas-cut erosion", "action": "REPLACE"},
            ],
        ),
        "140 mm Tank Gun": FirearmLifecycleConfig(
            platform="140 mm Tank Gun",
            category="crew_served",
            cartridge_key="140mm_KE",
            action="vertical sliding-block breech, ETC",
            barrel_length_mm=5500.0,
            peak_pressure_MPa=199.0,
            muzzle_velocity_ms=1698.0,
            projectile_mass_g=6400.0,
            propellant_mass_g=18_000.0,
            weapon_mass_kg=3400.0,
            bolt_mass_kg=45.0,
            spring_rate_N_per_mm=120.0,
            bolt_stroke_mm=280.0,
            bolt_impulse_Ns=49.0,
            muzzle_brake_efficiency=0.55,
            shooter_effective_mass_kg=3400.0,
            barrel_r_i_mm=70.0,
            barrel_r_o_mm=120.0,
            barrel_yield_MPa=900.0,
            archard_K=1.0e-17,
            archard_H_GPa=25.0,
            spring_tau_max_MPa=250.0,
            spring_S_e_MPa=650.0,
            bore_life_target_rounds=700,
            tier2_equipped=True,
            failure_rates={
                "FTFeed": 200_000, "FTExtract": 150_000, "FTFire": 8_000,
                "FTEject": 180_000, "FTGas": 50_000, "FTPrimer": 12_000,
                "FTCase": 25_000,
            },
            components=[
                {"name": "Stellite-21 bore liner (chrome clad)", "warn_rds": 500,
                 "fail_rds": 700, "model": "Throat erosion @ ETC pulse", "action": "RELINE"},
                {"name": "Sliding-block breech (maraging steel)", "warn_rds": 800,
                 "fail_rds": 2_000, "model": "Lug bearing + gas seal", "action": "INSPECT"},
                {"name": "Hydraulic recoil system (600 mm stroke)", "warn_rds": 400,
                 "fail_rds": 1_000, "model": "Seal pack + fluid degradation", "action": "SERVICE"},
                {"name": "ETC plasma injector electrodes", "warn_rds": 200,
                 "fail_rds": 500, "model": "Arc erosion per shot", "action": "REPLACE"},
                {"name": "Thermal sleeve / fume extractor", "warn_rds": 600,
                 "fail_rds": 1_500, "model": "Erosion + carbon fouling", "action": "SERVICE"},
            ],
        ),
    }


def _generic_configs() -> Dict[str, GenericLifecycleConfig]:
    return {
        "APES Body Armour": GenericLifecycleConfig(
            platform="APES Body Armour",
            category="armour",
            primary_metric="calendar_years",
            headline={
                "panel_service_life_yr": 12,
                "ceramic_tile_replacement_yr": 5,
                "soft_panel_refresh_yr": 8,
                "strike_face_dlc_recoat_yr": 3,
            },
            components=[
                {"name": "B4C dragon-scale tile array", "warn": 4, "fail": 5,
                 "unit": "yr", "model": "Tile fracture + edge spall", "action": "REPLACE_TILES"},
                {"name": "16-layer Kevlar/UHMWPE soft stack", "warn": 6, "fail": 8,
                 "unit": "yr", "model": "UV + flex fatigue", "action": "REPLACE_PANEL"},
                {"name": "Non-Newtonian shear-thickening pad", "warn": 3, "fail": 5,
                 "unit": "yr", "model": "Polymer chain scission", "action": "REPLACE_PAD"},
                {"name": "Titanium strike-point inserts", "warn": 8, "fail": 12,
                 "unit": "yr", "model": "Peening + DLC wear", "action": "INSPECT"},
            ],
        ),
        "APES-L Mark I Body Armour": GenericLifecycleConfig(
            platform="APES-L Mark I Body Armour",
            category="armour",
            primary_metric="calendar_years",
            headline={
                "panel_service_life_yr": 10,
                "ceramic_tile_replacement_yr": 4,
                "soft_panel_refresh_yr": 6,
            },
            components=[
                {"name": "8 mm B4C tile (police panel)", "warn": 3, "fail": 4,
                 "unit": "yr", "model": "Multi-hit spall", "action": "REPLACE_TILES"},
                {"name": "10-layer soft stack (22 kg/m²)", "warn": 4, "fail": 6,
                 "unit": "yr", "model": "Duty-cycle flex fatigue", "action": "REPLACE_PANEL"},
                {"name": "Carrier mesh + MOLLE webbing", "warn": 2, "fail": 4,
                 "unit": "yr", "model": "Abrasion + UV", "action": "REPLACE_CARRIER"},
            ],
        ),
        "NACS CBRN": GenericLifecycleConfig(
            platform="NACS CBRN",
            category="systems",
            primary_metric="calendar_months",
            headline={
                "filter_cartridge_life_mo": 6,
                "suit_fabric_service_yr": 5,
                "valve_diaphragm_service_mo": 12,
            },
            components=[
                {"name": "Activated-carbon / HEPA filter canister", "warn": 4, "fail": 6,
                 "unit": "mo", "model": "Breakthrough time @ 5 mg/m³", "action": "REPLACE"},
                {"name": "Butyl / PTFE laminate suit", "warn": 3, "fail": 5,
                 "unit": "yr", "model": "Permeation + seam fatigue", "action": "REPLACE"},
                {"name": "Exhalation valve diaphragm", "warn": 8, "fail": 12,
                 "unit": "mo", "model": "Elastomer set + tear", "action": "REPLACE"},
            ],
        ),
        "AlNiCyN Armour": GenericLifecycleConfig(
            platform="AlNiCyN Armour",
            category="armour",
            primary_metric="calendar_years",
            headline={
                "plate_service_life_yr": 15,
                "spall_liner_refresh_yr": 7,
                "areal_density_kg_m2": 28,
            },
            components=[
                {"name": "AlNiCyN reaction-sintered tile", "warn": 10, "fail": 15,
                 "unit": "yr", "model": "Micro-crack + moisture ingress", "action": "REPLACE"},
                {"name": "UHMWPE spall liner", "warn": 5, "fail": 7,
                 "unit": "yr", "model": "Delamination", "action": "REPLACE"},
            ],
        ),
        "ADF Tactical Field Kit": GenericLifecycleConfig(
            platform="ADF Tactical Field Kit",
            category="sustainment",
            primary_metric="calendar_years",
            headline={
                "load_carriage_fabric_yr": 8,
                "hydration_bladder_yr": 2,
                "IFAK_sterile_pack_mo": 36,
            },
            components=[
                {"name": "500D Cordura load carriage", "warn": 5, "fail": 8,
                 "unit": "yr", "model": "Abrasion + UV", "action": "REPLACE"},
                {"name": "Hydration bladder (TPU)", "warn": 1, "fail": 2,
                 "unit": "yr", "model": "Biofilm + seam leak", "action": "REPLACE"},
                {"name": "Sterile IFAK consumables", "warn": 24, "fail": 36,
                 "unit": "mo", "model": "Sterility expiry", "action": "CONSUME"},
            ],
        ),
        "Caseless Bullets (BPC)": GenericLifecycleConfig(
            platform="Caseless Bullets (BPC)",
            category="sustainment",
            primary_metric="calendar_months",
            headline={
                "protein_case_shelf_mo": 24,
                "cook_off_safe_temp_C": 93,
                "humidity_storage_max_pct": 60,
            },
            components=[
                {"name": "Protein-cased round (BPC)", "warn": 18, "fail": 24,
                 "unit": "mo", "model": "Protein denaturation + moisture", "action": "CONSUME"},
                {"name": "Nitrocellulose propellant wafer", "warn": 18, "fail": 30,
                 "unit": "mo", "model": "Stabilizer depletion", "action": "CONSUME"},
            ],
        ),
        "Combat Drug": GenericLifecycleConfig(
            platform="Combat Drug",
            category="sustainment",
            primary_metric="calendar_months",
            headline={
                "depot_shelf_cold_chain_mo": 36,
                "room_temp_hold_hr": 72,
                "autoinjector_shelf_mo": 24,
            },
            components=[
                {"name": "HSX7 depot ampoule (2–8 °C)", "warn": 30, "fail": 36,
                 "unit": "mo", "model": "Peptide aggregation", "action": "CONSUME"},
                {"name": "Autoinjector mechanism", "warn": 18, "fail": 24,
                 "unit": "mo", "model": "Spring + seal ageing", "action": "REPLACE"},
            ],
        ),
        "HEL-CMS/DB": GenericLifecycleConfig(
            platform="HEL-CMS/DB",
            category="systems",
            primary_metric="operating_hours",
            headline={
                "diode_array_life_hr": 10_000,
                "coolant_pump_service_hr": 5_000,
                "beam_window_recoat_hr": 2_000,
            },
            components=[
                {"name": "Fiber-coupled diode stack", "warn": 8_000, "fail": 10_000,
                 "unit": "hr", "model": "Junction degradation @ 40 kW", "action": "REPLACE"},
                {"name": "Deionised coolant loop pump", "warn": 3_500, "fail": 5_000,
                 "unit": "hr", "model": "Seal + bearing wear", "action": "OVERHAUL"},
                {"name": "Fused-silica output window (DLC)", "warn": 1_500, "fail": 2_000,
                 "unit": "hr", "model": "Plasma pitting", "action": "RECOAT"},
            ],
        ),
        "HPR-X Rocketry": GenericLifecycleConfig(
            platform="HPR-X Rocketry",
            category="systems",
            primary_metric="flight_cycles",
            headline={
                "motor_case_life_flights": 50,
                "nozzle_insert_life_flights": 30,
                "avionics_battery_cycles": 200,
            },
            components=[
                {"name": "CFRP motor case (152 mm)", "warn": 35, "fail": 50,
                 "unit": "flights", "model": "Pressure-cycle fatigue", "action": "RETIRE"},
                {"name": "Graphite nozzle insert", "warn": 20, "fail": 30,
                 "unit": "flights", "model": "Ablation + throat growth", "action": "REPLACE"},
                {"name": "GPS / INS avionics battery", "warn": 150, "fail": 200,
                 "unit": "cycles", "model": "Li-ion capacity fade", "action": "REPLACE"},
            ],
        ),
        "Hearing Protection": GenericLifecycleConfig(
            platform="Hearing Protection",
            category="systems",
            primary_metric="calendar_months",
            headline={
                "foam_plug_life_mo": 6,
                "electronic_muff_seal_mo": 24,
                "earplug_NRR_derated_dB": 22,
            },
            components=[
                {"name": "Slow-recovery foam earplug", "warn": 4, "fail": 6,
                 "unit": "mo", "model": "Cell collapse + contamination", "action": "REPLACE"},
                {"name": "Electronic muff gel seal", "warn": 18, "fail": 24,
                 "unit": "mo", "model": "Elastomer hardening", "action": "REPLACE_PADS"},
            ],
        ),
        "Injectable Nutrition": GenericLifecycleConfig(
            platform="Injectable Nutrition",
            category="sustainment",
            primary_metric="calendar_months",
            headline={
                "formulation_shelf_25C_mo": 18,
                "osmolality_limit_mOsm_kg": 600,
                "cold_chain_shelf_mo": 30,
            },
            components=[
                {"name": "Peripheral-safe isotonic bag", "warn": 12, "fail": 18,
                 "unit": "mo", "model": "Lipid oxidation Q10", "action": "CONSUME"},
                {"name": "Central-line hypertonic vial", "warn": 24, "fail": 30,
                 "unit": "mo", "model": "Cold-chain integrity", "action": "CONSUME"},
            ],
        ),
        "Military Command Doctrine": GenericLifecycleConfig(
            platform="Military Command Doctrine",
            category="scope",
            scope_note="Doctrinal force-structure and training-duration targets — no physics lifecycle model.",
            headline={},
            components=[],
        ),
        "TACS Military Noise Cancellation": GenericLifecycleConfig(
            platform="TACS Military Noise Cancellation",
            category="systems",
            primary_metric="calendar_years",
            headline={
                "wearable_array_service_yr": 8,
                "vehicle_array_service_yr": 10,
                "battery_cycle_life": 500,
            },
            components=[
                {"name": "16-element wearable ANC array", "warn": 6, "fail": 8,
                 "unit": "yr", "model": "MEMS mic drift + flex fatigue", "action": "CALIBRATE"},
                {"name": "Vehicle roof phased array", "warn": 7, "fail": 10,
                 "unit": "yr", "model": "Vibration + connector corrosion", "action": "SERVICE"},
                {"name": "Li-poly wearable battery", "warn": 400, "fail": 500,
                 "unit": "cycles", "model": "Capacity fade @ 1C", "action": "REPLACE"},
            ],
        ),
        "OBSIDIAN Body Armour": GenericLifecycleConfig(
            platform="OBSIDIAN Body Armour",
            category="scope",
            scope_note="Hypothetical carbyne / STF suit — no runnable ballistic lifecycle model.",
            headline={},
            components=[],
        ),
        "OBSIDIAN-X Body Armour": GenericLifecycleConfig(
            platform="OBSIDIAN-X Body Armour",
            category="scope",
            scope_note="Full-body hypothetical armour — no runnable lifecycle model.",
            headline={},
            components=[],
        ),
        "Rubber Tank Tracks": GenericLifecycleConfig(
            platform="Rubber Tank Tracks",
            category="systems",
            primary_metric="distance_km",
            headline={
                "rubber_pad_life_km": 8000,
                "road_wheel_bearing_km": 12_000,
                "net_noise_reduction_dB": 20.8,
            },
            components=[
                {"name": "Segmented rubber road-wheel pad", "warn": 6_000, "fail": 8_000,
                 "unit": "km", "model": "Chunking + heat build-up", "action": "REPLACE"},
                {"name": "Road-wheel bearing cartridge", "warn": 9_000, "fail": 12_000,
                 "unit": "km", "model": "Roller fatigue + seal", "action": "OVERHAUL"},
                {"name": "Torsion bar bushing (elastomer)", "warn": 5_000, "fail": 7_500,
                 "unit": "km", "model": "Compression set", "action": "REPLACE"},
            ],
        ),
        "TACT-1 Mark II Ration": GenericLifecycleConfig(
            platform="TACT-1 Mark II Ration",
            category="sustainment",
            primary_metric="calendar_months",
            headline={
                "shelf_life_25C_mo": 36,
                "shelf_life_49C_mo": 12,
                "shelf_life_4C_mo": 48,
            },
            components=[
                {"name": "Main meal retort pouch", "warn": 30, "fail": 36,
                 "unit": "mo", "model": "Q10 lipid oxidation @ 25 °C", "action": "CONSUME"},
                {"name": "Electrolyte / snack bar", "warn": 24, "fail": 30,
                 "unit": "mo", "model": "Moisture ingress", "action": "CONSUME"},
                {"name": "Flameless ration heater (Mg-Fe)", "warn": 48, "fail": 60,
                 "unit": "mo", "model": "Mg powder oxidation", "action": "CONSUME"},
            ],
        ),
        "ASNP Sports Nutrition": GenericLifecycleConfig(
            platform="ASNP Sports Nutrition",
            category="sustainment",
            primary_metric="calendar_months",
            headline={
                "product_shelf_mo": 24,
                "opened_container_days": 30,
            },
            components=[
                {"name": "Electrolyte powder sachet", "warn": 18, "fail": 24,
                 "unit": "mo", "model": "Clumping + vitamin degradation", "action": "CONSUME"},
                {"name": "Protein / carb gel pouch", "warn": 12, "fail": 18,
                 "unit": "mo", "model": "Maillard browning", "action": "CONSUME"},
            ],
        ),
        "TAIPAN-1 Missile": GenericLifecycleConfig(
            platform="TAIPAN-1 Missile",
            category="scope",
            scope_note="Flight dynamics validated by taipan1_sim.py — no portfolio §23 lifecycle slice.",
            headline={"certified_storage_yr": 10, "motor_burn_s": 4.2},
            components=[
                {"name": "Solid booster grain", "warn": 8, "fail": 10,
                 "unit": "yr", "model": "AP/HTPB ageing", "action": "RETIRE"},
            ],
        ),
        "CL-20 High Explosive": GenericLifecycleConfig(
            platform="CL-20 High Explosive",
            category="sustainment",
            primary_metric="calendar_months",
            headline={
                "cold_storage_shelf_mo": 240,
                "room_temp_hold_days": 14,
                "stabilizer_depletion_pct_yr": 0.5,
            },
            components=[
                {"name": "CL-20 pressed pellet lot", "warn": 180, "fail": 240,
                 "unit": "mo", "model": "Stabilizer @ −18 °C", "action": "CONSUME"},
                {"name": "PBX binder batch", "warn": 120, "fail": 180,
                 "unit": "mo", "model": "HMX / binder phase separation", "action": "CONSUME"},
            ],
        ),
    }


# platform_id (sim_common) → lifecycle platform display name
PLATFORM_ID_TO_LIFECYCLE: Dict[str, str] = {
    "mp46m_guardian_pistol": "MP-4.6M Pistol",
    "mp46p_guardian_le": "MP-4.6P Guardian LE",
    "mp46m_defender_pdw": "MP-4.6M Defender PDW",
    "mp68_mark_ii_rifle": "MP-6.8 Mark II Rifle",
    "mas152e_sniper": "MAS-15.2E Sniper",
    "57mm_autocannon": "57 mm Autocannon",
    "57mm_underbarrel_grenade": "57 mm Underbarrel GL",
    "57mm_mortar_rpg": "57 mm Mortar/RPG",
    "140mm_tank_ke": "140 mm Tank Gun",
    "apes_body_armour": "APES Body Armour",
    "apes_l_body_armour": "APES-L Mark I Body Armour",
    "nacs_cbrn": "NACS CBRN",
    "alnicyn_armour": "AlNiCyN Armour",
    "adf_tactical_field_kit": "ADF Tactical Field Kit",
    "caseless_bullets": "Caseless Bullets (BPC)",
    "combat_drug": "Combat Drug",
    "hel_cms_db": "HEL-CMS/DB",
    "hprx_rocketry": "HPR-X Rocketry",
    "hearing_protection": "Hearing Protection",
    "injectable_nutrition": "Injectable Nutrition",
    "military_command_doctrine": "Military Command Doctrine",
    "military_noise_cancellation": "TACS Military Noise Cancellation",
    "obsidian_body_armour": "OBSIDIAN Body Armour",
    "obsidian_x_body_armour": "OBSIDIAN-X Body Armour",
    "rubber_tank_tracks": "Rubber Tank Tracks",
    "tact1_ration": "TACT-1 Mark II Ration",
    "asnp_sports_nutrition": "ASNP Sports Nutrition",
    "taipan_missile": "TAIPAN-1 Missile",
    "cl20_high_explosive": "CL-20 High Explosive",
}
