#!/usr/bin/env python3
"""
Emit C++ translation unit with Bessel ratio lookup tables matching cypha_accel/nig_gh.py / Cypha.py.

- K2/K1 — used for E[1/V] (GIG lambda=-1)
- K0/K1 — used for E[V] (GIG lambda=-1), for `_nig_adapt` / GH session chi

Run from repo root after installing scipy + numpy:
  python scripts/gen_native_bessel_table.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
_OUT = _ROOT / "native" / "src" / "bessel_table_data.cpp"

try:
    from scipy.special import kv as _kv_init

    _BESSEL_X = np.linspace(1e-6, 120.0, 16384)
    _K2v = _kv_init(2.0, _BESSEL_X)
    _K1v = _kv_init(1.0, _BESSEL_X)
    _K2_K1_TABLE = (_K2v / np.maximum(_K1v, 1e-300)).astype(np.float64)
    _K0v = _kv_init(0.0, _BESSEL_X)
    _K0_K1_TABLE = (_K0v / np.maximum(_K1v, 1e-300)).astype(np.float64)
except Exception as e:  # pragma: no cover
    raise SystemExit(f"scipy required: {e}") from e


def main() -> None:
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    xs = _BESSEL_X.tolist()
    r2 = _K2_K1_TABLE.tolist()
    r0 = _K0_K1_TABLE.tolist()
    lines = [
        '// AUTO-GENERATED by scripts/gen_native_bessel_table.py — do not edit.',
        '#include "cypha/bessel_table.hpp"',
        '',
        'namespace cypha::detail {',
        '',
        'const double kBesselX[kBesselN] = {',
    ]
    lines.append("  " + ",\n  ".join(f"{v:.17e}" for v in xs))
    lines.append("};")
    lines.append("")
    lines.append("const double kBesselK2K1[kBesselN] = {")
    lines.append("  " + ",\n  ".join(f"{v:.17e}" for v in r2))
    lines.append("};")
    lines.append("")
    lines.append("const double kBesselK0K1[kBesselN] = {")
    lines.append("  " + ",\n  ".join(f"{v:.17e}" for v in r0))
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace cypha::detail")
    lines.append("")
    _OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {_OUT}")


if __name__ == "__main__":
    main()
