#!/usr/bin/env python3
"""Emit parity_fixtures/preprocessor/ for native Preprocessor.transform_one."""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))

from cypha_studio.core.dataset import Preprocessor

_FIX = _ROOT / "parity_fixtures" / "preprocessor"


def main() -> None:
    _FIX.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(7)
    X = rng.normal(0, 1, (80, 5)).astype(np.float64)
    pre = Preprocessor(scale=True, pca_dim=3, rff_dim=16, rff_gamma=0.5, seed=11)
    pre.fit(X)
    x_one = rng.normal(0, 0.5, 5).astype(np.float64)
    y_exp = pre.transform_one(x_one)

    state = pre.save_state()
    (_FIX / "preprocessor.json").write_text(json.dumps(state, indent=2), encoding="utf-8")
    side = {"x": x_one.tolist(), "expected": y_exp.tolist()}
    (_FIX / "sidecar.json").write_text(json.dumps(side, indent=2), encoding="utf-8")
    (_FIX / "README.md").write_text(
        "# Preprocessor parity\n\n"
        "Generated by `scripts/generate_preprocessor_parity.py`.\n",
        encoding="utf-8",
    )
    print(f"Wrote {_FIX}/")


if __name__ == "__main__":
    main()
