#!/usr/bin/env python3
"""
Emit parity_fixtures/memory_train/ for native DIFMemory.train.

Run from repo root:
  python scripts/generate_memory_train_parity.py
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))

from Cypha import CyphaDIF, VectorEncoder, cypha_load_binary, cypha_save_binary

_FIX = _ROOT / "parity_fixtures" / "memory_train"


def main() -> None:
    _FIX.mkdir(parents=True, exist_ok=True)
    ref = _ROOT / "parity_fixtures" / "reference.cypha"
    if not ref.is_file():
        raise SystemExit("Run scripts/generate_parity_fixtures.py first")

    state = cypha_load_binary(str(ref))
    clf = CyphaDIF(
        VectorEncoder(8),
        field_dim=24,
        rng=np.random.default_rng(0),
    )
    clf.load_state(state)

    exp = np.load(_ROOT / "parity_fixtures" / "expected.npz")
    x = exp["x_input"][0]
    label = "1"
    h, _f = clf._encode(x)
    h_field = clf.field.h

    classes = list(clf.memory._classes.keys())
    if label not in classes:
        classes.append(label)
    ctx_prior = clf._ctx_prior(classes)

    _pred, _ok, loss, _post_llrs, _post_conf = clf.memory.train(
        h,
        label,
        h_field=h_field,
        context_prior=ctx_prior,
        temperature=float(clf.temperature),
        ood_sigma=float(clf.ood_sigma),
        world_lr=float(clf.world_lr),
        delta_lr=float(clf.delta_lr),
    )

    shutil.copyfile(ref, _FIX / "before.cypha")
    cypha_save_binary(clf.save_state(), str(_FIX / "after.cypha"))

    sidecar = {
        "h": h.tolist(),
        "h_field": np.asarray(h_field, dtype=np.float64).tolist(),
        "label": label,
        "temperature": float(clf.temperature),
        "ood_sigma": float(clf.ood_sigma),
        "world_lr": float(clf.world_lr),
        "delta_lr": float(clf.delta_lr),
        "context_prior": ctx_prior,
        "expected_loss": float(loss),
        "f_field": clf.memory.world.F_field.astype(np.float64).tolist(),
        "field_dim": int(clf.field_dim),
    }
    (_FIX / "sidecar.json").write_text(json.dumps(sidecar, indent=2), encoding="utf-8")

    readme = _FIX / "README.md"
    readme.write_text(
        "# Memory train parity\n\n"
        "Generated by `scripts/generate_memory_train_parity.py`.\n\n"
        "- `before.cypha` — copy of `parity_fixtures/reference.cypha`\n"
        "- `after.cypha` — state after one `DIFMemory.train` call (includes `field_a_eff` when `field_W_T` is present)\n"
        "- `sidecar.json` — `h`, `h_field`, hyperparameters, `context_prior`, `f_field`\n",
        encoding="utf-8",
    )
    print(f"Wrote {_FIX}/")


if __name__ == "__main__":
    main()
